import {test,expect} from '@playwright/test';
const note='BBBBBBBB-BBBB-4BBB-8BBB-000000000002';
test('supplement uses the shared modal and saves all fields together',async({page})=>{
  await page.setViewportSize({width:390,height:700});
  await page.goto(`/notes/${note}?panel=1`);
  await expect(page.locator('.note-edit-details')).toHaveCount(0);
  await page.locator('.note-detail-heading .session-more > summary').click();
  await page.getByRole('button',{name:'编辑补充信息'}).click();
  const modal=page.getByRole('dialog',{name:'编辑补充信息'});await expect(modal).toBeVisible();await expect(modal).toHaveCSS('opacity','1');
  await expect(modal).toHaveCSS('scrollbar-width','none');
  await page.locator('#supplement-note').fill('补充判断');await page.locator('#supplement-question').fill('原始问题');
  await page.locator('#supplement-url').fill('https://example.com/source');
  await page.screenshot({path:`artifacts/note-supplement-${test.info().project.name}.png`});
  await modal.getByRole('button',{name:'保存',exact:true}).click();await expect(modal).toHaveCount(0);
  const clip=(await(await page.request.get(`/api/clips/${note}`)).json()).clip;
  expect(clip.note).toBe('补充判断');expect(clip.question).toBe('原始问题');expect(clip.sourceURL).toBe('https://example.com/source');
});
test('formatting menu inserts and deletes images and file links',async({page})=>{
  const clip=(await(await page.request.get(`/api/clips/${note}`)).json()).clip;
  expect((await page.request.put(`/api/clips/${note}`,{headers:{'X-Rewind-Request':'1'},data:{body:'编辑测试正文',version:clip.version}})).ok()).toBe(true);
  await page.route('https://example.com/note-test.png', route => route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="180" height="240"><rect width="180" height="240" fill="#dce5d7"/></svg>'}));
  await page.setViewportSize({width:390,height:850});
  await page.goto(`/notes/${note}?panel=1`);
  const editor=page.getByRole('textbox',{name:'编辑笔记正文'}).first();await editor.click();
  await editor.press('ControlOrMeta+A');
  const toolbar=page.getByRole('toolbar',{name:'正文格式'});await expect(toolbar).toBeVisible();
  await toolbar.getByRole('button',{name:'图片',exact:true}).click();
  await page.locator('#insert-content-url').fill('https://example.com/note-test.png');
  await page.locator('#insert-content-label').fill('测试图片');
  await page.getByRole('dialog').getByRole('button',{name:'插入',exact:true}).click();
  const img=editor.locator('img[alt="测试图片"]');await expect(img).toHaveCount(1);
  await img.click();
  await expect(editor).toHaveClass(/ProseMirror-hideselection/);
  await expect(img).toHaveCSS('outline-width','1px');
  expect(await img.evaluate(el=>getComputedStyle(el,'::selection').backgroundColor)).toBe('rgba(0, 0, 0, 0)');
  await page.screenshot({path:`artifacts/image-selection-${test.info().project.name}.png`});
  await toolbar.getByRole('button',{name:'删除图片',exact:true}).click();await expect(img).toHaveCount(0);
  await editor.click();await editor.pressSequentially('文件占位');await editor.press('ControlOrMeta+A');
  await toolbar.getByRole('button',{name:'文件 / 链接',exact:true}).click();
  await page.locator('#insert-content-url').fill('https://example.com/test.pdf');await page.locator('#insert-content-label').fill('测试文件');
  await page.getByRole('dialog').getByRole('button',{name:'插入',exact:true}).click();
  const link=editor.locator('a[href="https://example.com/test.pdf"]');await expect(link).toBeVisible();await link.click();await editor.press('ControlOrMeta+A');
  await toolbar.getByRole('button',{name:'删除文件或链接',exact:true}).click();await expect(link).toHaveCount(0);
  await editor.click();await editor.pressSequentially('格式验证');await editor.press('ControlOrMeta+A');const bold=toolbar.getByRole('button',{name:'加粗',exact:true});if(await bold.getAttribute('aria-pressed')==='true') await bold.click();await bold.click();
  await expect(editor.locator('strong').first()).toBeVisible();
  await page.screenshot({path:`artifacts/note-format-${test.info().project.name}.png`});
  await page.locator('.note-banner').click();await expect(page.getByRole('status')).toContainText('已保存到本机');
  await page.reload();await expect(page.locator('img[alt="测试图片"]')).toHaveCount(0);await expect(page.locator('a[href="https://example.com/test.pdf"]')).toHaveCount(0);
});
